export const CATEGORIES = [
  { id: "new-arrivals", name: "신상품", count: 0, description: "최신 신상품 컬렉션" },
  { id: "brand", name: "브랜드", count: 0, description: "브랜드별 럭셔리 컬렉션" },
  { id: "gender", name: "성별", count: 0, description: "성별 맞춤 컬렉션" },
  { id: "clothing", name: "의류", count: 0, description: "프리미엄 의류 컬렉션" },
  { id: "bags", name: "가방", count: 0, description: "시그니처 럭셔리 백 컬렉션" },
  { id: "wallets", name: "지갑", count: 0, description: "프리미엄 가죽 지갑 컬렉션" },
  { id: "shoes", name: "신발", count: 0, description: "럭셔리 브랜드 신발 컬렉션" },
  { id: "watches", name: "시계", count: 0, description: "타임리스 럭셔리 워치 컬렉션" },
  { id: "golf", name: "골프", count: 0, description: "프리미엄 골프 컬렉션" },
  { id: "jewelry", name: "쥬얼리/잡화", count: 0, description: "쥬얼리 및 잡화 컬렉션" },
  { id: "sameday", name: "당일배송", count: 0, description: "당일배송 가능 상품" },
  { id: "sale", name: "할인상품", count: 0, description: "특별 할인 상품" },
  { id: "best", name: "베스트상품", count: 0, description: "인기 베스트 상품" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "루이비통 네버풀 MM",
    price: "890,000",
    category: "bags",
    isBest: true,
    isNew: false,
  },
  {
    id: 2,
    name: "구찌 마몬트 숄더백",
    price: "720,000",
    category: "bags",
    isBest: true,
    isNew: false,
  },
  {
    id: 3,
    name: "샤넬 클래식 플랩백",
    price: "1,450,000",
    category: "bags",
    isBest: true,
    isNew: true,
  },
  {
    id: 4,
    name: "디올 새들백",
    price: "680,000",
    category: "bags",
    isBest: false,
    isNew: true,
  },
  {
    id: 5,
    name: "몽클레어 마야 패딩",
    price: "580,000",
    category: "clothing",
    isBest: true,
    isNew: false,
  },
  {
    id: 6,
    name: "캐나다구스 원정대 파카",
    price: "720,000",
    category: "clothing",
    isBest: true,
    isNew: false,
  },
  {
    id: 7,
    name: "막스마라 테디 코트",
    price: "890,000",
    category: "clothing",
    isBest: true,
    isNew: false,
  },
  {
    id: 8,
    name: "버버리 트렌치 코트",
    price: "650,000",
    category: "clothing",
    isBest: false,
    isNew: true,
  },
];

export const NOTICE_DATA = [
  { id: 1, title: "[공지] 2025년 연말 배송 안내", date: "2025-12-15" },
  { id: 2, title: "신상품 입고 안내 - 25SS 컬렉션", date: "2025-12-10" },
  { id: 3, title: "시스템 점검 안내 (12/20 02:00 ~ 06:00)", date: "2025-12-18" },
  { id: 4, title: "회원등급 혜택 안내", date: "2025-11-25" },
  { id: 5, title: "정품 인증 서비스 도입 안내", date: "2025-11-10" },
];
