export const CATEGORIES = [
  { id: "outer", name: "아우터", count: 42, description: "라이크잇이 엄선한 프리미엄 아우터 컬렉션" },
  { id: "padding", name: "패딩", count: 35, description: "따뜻함과 스타일을 동시에, 고급 패딩 컬렉션" },
  { id: "tops", name: "상의", count: 58, description: "데일리부터 포멀까지, 다양한 상의 컬렉션" },
  { id: "bottoms", name: "하의", count: 45, description: "완벽한 핏의 팬츠 & 스커트 컬렉션" },
  { id: "shoes", name: "신발", count: 32, description: "럭셔리 브랜드 신발 컬렉션" },
  { id: "accessories", name: "악세사리", count: 28, description: "디테일을 완성하는 액세서리" },
  { id: "wallets", name: "지갑", count: 24, description: "프리미엄 가죽 지갑 컬렉션" },
  { id: "bags", name: "가방", count: 56, description: "시그니처 럭셔리 백 컬렉션" },
  { id: "watches", name: "시계", count: 18, description: "타임리스 럭셔리 워치 컬렉션" },
  { id: "genuine", name: "정품", count: 15, description: "100% 정품 인증 상품" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "루이비통 네버풀 MM",
    price: "890,000",
    category: "bags",
    isBest: true,
    isNew: false,
  },
  {
    id: 2,
    name: "구찌 마몬트 숄더백",
    price: "720,000",
    category: "bags",
    isBest: true,
    isNew: false,
  },
  {
    id: 3,
    name: "샤넬 클래식 플랩백",
    price: "1,450,000",
    category: "bags",
    isBest: true,
    isNew: true,
  },
  {
    id: 4,
    name: "디올 새들백",
    price: "680,000",
    category: "bags",
    isBest: false,
    isNew: true,
  },
  {
    id: 5,
    name: "몽클레어 마야 패딩",
    price: "580,000",
    category: "padding",
    isBest: true,
    isNew: false,
  },
  {
    id: 6,
    name: "캐나다구스 원정대 파카",
    price: "720,000",
    category: "padding",
    isBest: true,
    isNew: false,
  },
  {
    id: 7,
    name: "막스마라 테디 코트",
    price: "890,000",
    category: "outer",
    isBest: true,
    isNew: false,
  },
  {
    id: 8,
    name: "버버리 트렌치 코트",
    price: "650,000",
    category: "outer",
    isBest: false,
    isNew: true,
  },
];

export const NOTICE_DATA = [
  { id: 1, title: "[공지] 2025년 연말 배송 안내", date: "2025-12-15" },
  { id: 2, title: "신상품 입고 안내 - 25SS 컬렉션", date: "2025-12-10" },
  { id: 3, title: "시스템 점검 안내 (12/20 02:00 ~ 06:00)", date: "2025-12-18" },
  { id: 4, title: "회원등급 혜택 안내", date: "2025-11-25" },
  { id: 5, title: "정품 인증 서비스 도입 안내", date: "2025-11-10" },
];
